version: '3.3'
services:
    app:
        image: 'prograweb-frontend'
        build: C:\Users\JulioCarpio\Desktop\Lab2\Laboratorio2\Laboratorio2
        ports:
            - 4200:80
    express: # name of the second service
        build: '.' # specify the directory of the Dockerfile
        ports:
            - "3001:3001" #specify ports mapping
        links:
            - hostmongo # link this service to the database service
            - hostredis
    hostredis:
        image: redis
        ports:
            - "6379:6379"
    hostmongo: # name of the third service
        image: mongo # specify image to build container from
        ports:
            - "27017:27017" # specify port forwarding